#data ingestion related configurations
artifacts_root: artifacts #setting artifacts folder

#creating directory to store the images downloaded from source
#storing after unzipping into specified directory
data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/entbappy/Branching-tutorial/raw/master/Chicken-fecal-images.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion